name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Test on ${{ matrix.os }}, 🐍=${{ matrix.python-version }}, Program=${{ matrix.conda-env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.8", "3.9", "3.10"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Create Environment
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: fegrow
        environment-file: env.yml
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true
        mamba-version: "*"
        miniforge-version: latest
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: env summary
      shell: bash -l {0}
      run: conda list
    - name: dry install fegrow
      shell: bash -l {0}
      run: pip install --dry-run .
    - name: install fegrow
      shell: bash -l {0}
      run: pip install .
    - name: install pytest
      shell: bash -l {0}
      run: mamba install pytest
    - name: pytest
      shell: bash -l {0}
      run: pytest fegrow/testing
    - name: Run tutorial.py
      shell: bash -l {0}
      run: |
        cd notebooks
        obabel sarscov2/lig.pdb -O sarscov2/coreh.sdf -p 7
        wget -nc https://files.rcsb.org/download/7L10.pdb        
        python .tutorial.py
